### ISSUE TITLE
Bug for reputation in TWW pre patch

### ISSUE THREAD

**Issue by DreamOfHero** [phyber/XPBarNone#5]
Message: Interface/AddOns/XPBarNone/Core.lua:1517: attempt to call upvalue 'GetWatchedFactionInfo' (a nil value)
Time: Sat Aug 10 21:52:43 2024
Count: 4
Stack: Interface/AddOns/XPBarNone/Core.lua:1517: attempt to call upvalue 'GetWatchedFactionInfo' (a nil value)
[string "@Interface/AddOns/XPBarNone/Core.lua"]:1517: in function `UpdateRepData'
[string "@Interface/AddOns/XPBarNone/Core.lua"]:1642: in function `UpdateXPBar'
[string "@Interface/AddOns/XPBarNone/Core.lua"]:906: in function `ToggleShowReputation'
[string "@Interface/AddOns/XPBarNone/Core.lua"]:1371: in function <Interface/AddOns/XPBarNone/Core.lua:1369>

Locals: self = <table> {
 modules = <table> {
 }
 baseName = "XPBarNone"
 cXP = 2875
 defaultModuleState = true
 enabledState = true
 frame = XPBarNoneFrame {
 }
 defaultModuleLibraries = <table> {
 }
 name = "XPBarNone"
 orderedModules = <table> {
 }
 diffXP = 2875
 remXP = 7460
 nXP = 10335
 db = <table> {
 }
}
(*temporary) = nil
(*temporary) = "attempt to call upvalue 'GetWatchedFactionInfo' (a nil value)"
db = <table> {
 general = <table> {
 }
 azerite = <table> {
 }
 colours = <table> {
 }
 repmenu = <table> {
 }
 xp = <table> {
 }
 rep = <table> {
 }
}
GetWatchedFactionInfo = nil
L = <table> {
 Set the font. = "Set the font."
 Set the bar width. = "Set the bar width."
 Hide the text on the XP and Rep bars. = "Hide the text on the XP and Rep bars."
 Scale = "Scale"
 Show the azerite bar instead of the XP bar when on max level. = "Show the azerite bar instead of the XP bar when on max level."
 Resting = "Resting"
 Toggle the border. = "Toggle the border."
 Toggle bubbles on the XP bar. = "Toggle bubbles on the XP bar."
 Azerite item not found! = "Azerite item not found!"
 Text Position = "Text Position"
 Dynamic Bars = "Dynamic Bars"
 Profiles = "Profiles"
 Show zero values in the various Need tags, instead of an empty string = "Show zero values in the various Need tags, instead of an empty string"
 Commify = "Commify"
 Change the size of the text. = "Change the size of the text."
 Auto Hide Delay = "Auto Hide Delay"
 Bar Colours = "Bar Colours"
 Font Size = "Font Size"
 Reputation Bar related options = "Reputation Bar related options"
 Bubbles = "Bubbles"
 Experience Bar related options = "Experience Bar related options"
 Customise Text = "Customise Text"
 Set the colour of the XP text. = "Set the colour of the XP text."
 Set the bar height. = "Set the bar height."
 XP Text = "XP Text"
 Reputation Bar = "Reputation Bar"
 Lock = "Lock"
 Customise the Azerite text string. = "Customise the Azerite text string."
 Toggle screen clamping. = "Toggle screen clamping."
 Set the colour of the Reputation text. = "Set the colour of the Reputation text."
 Font Outline = "Font Outline"
 Set the bar scale. = "Set the bar scale."
 Font = "Font"
 Experience = "Experience"
 Toggle the locking. = "Toggle the locking."
 Frame Strata = "Frame Strata"
 Select the position of the text on XPBarNone. = "Select the position of the text on XPBarNone."
 Screen Clamp = "Screen Clamp"
 Mouse Over = "Mouse Over"
 Toggle the display of remaining rested XP. = "Toggle the display of remaining rested XP."
 Toggle the rest indication. = "Toggle the rest indication."
 Auto Watch Reputation = "Auto Watch Reputation"
 XP Bar = "XP Bar"
 Texture = "Texture"
 Automatically track your guild reputation increases. = "Automatically track your guild reputation increases."
 Set the colour of the background bar. = "Set the colour of the background bar."
 Set the length of time (in seconds) it takes for the menu to disappear once you move the mouse away. = "Set the length of time (in seconds) it takes for the menu to disappear once you move the mouse away."
 Width = "Width"
 Click to expand %s faction listing = "Click to expand %s faction listing"
 You need to select a faction to watch. = "You need to select a faction to watch."
 Standing: %s
Rep: %s/%s [%.1f%%] = "Standing: %s
Rep: %s/%s [%.1f%%]"
 Click to collapse %s faction listing = "Click to collapse %

**Comment by phyber** [comment]
This should be fixed in the most recent push.
